# Generated by Django 3.2.7 on 2023-03-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('total_bedroom', models.IntegerField()),
                ('total_washroom', models.IntegerField()),
                ('total_squarefeets', models.IntegerField()),
                ('house_image_1', models.ImageField(upload_to='', verbose_name='images/')),
                ('house_image_2', models.ImageField(upload_to='', verbose_name='images/')),
                ('house_image_3', models.ImageField(upload_to='', verbose_name='images/')),
                ('montly_rent', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('division', models.CharField(max_length=1000)),
                ('district', models.CharField(max_length=1000)),
                ('address_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
