# Generated by Django 3.2.7 on 2023-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=1000)),
                ('ssc_result', models.CharField(max_length=1000)),
                ('college_name', models.CharField(max_length=1000)),
                ('Hsc_result', models.CharField(max_length=200)),
                ('other_degree', models.TextField()),
                ('datetime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
